log-path = "./logs"
http-port = 80
url-path = ""

# title设置
[setting]
    title = "配置管理中心"

# WebServer管理
[admin]
    user = "admin"
    pass = "123"

# 数据库配置
[database]
    link = "mysql:root:123456@tcp(127.0.0.1:3306)/gmanager"

# gtoken配置文件
[gtoken]
    # 缓存模式 1 gcache 2 gredis
    cache-mode = 1
    # 是否支持多端登录
    multi-login = true


# Redis数据库配置
[redis]
  default = "127.0.0.1:16379,0,soccer"
  cache   = "127.0.0.1:16379,1,soccer?idleTimeout=600"